mysite/blog/urls.py
from django.conf.urls import url,include

from django.urls import path
from blog import views

# SET THE NAMESPACE!
app_name = 'basic_app'
urlpatterns = [
    url(r'register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
    

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,reverse_lazy
from django.conf.urls import url,include
from django.contrib.auth.urls import views as auth_views
from blog import views
from django.conf.urls.static import static

urlpatterns = [
     url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'register/',views.register,name='register'),
    path('',include('blog.urls')),
    path('user_login/',views.user_login,name='user_login'),
    path('logout/', views.user_logout, name='logout'),
    path('help/', views.help, name='help'),
    path('mainpageloggedin/',views.mainpageloggedin,name="mainpageloggedin"),
    path('mainpageloggedin/all_notes',views.display_notes,name="display_notes"),
    path('contactus/',views.contactus,name='contactus'),
    path('Contacting/',views.lastContact,name="lastContact"),
    path('update_task/<str:pk>',views.update,name="update_task"),
    path('delete/<str:pk>',views.delete,name="delete"),

    path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name="password_reset.html"),
     name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"), 
     name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"), 
        name="password_reset_complete"),
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.



class ContactUsInfo(models.Model):
    name=models.CharField(max_length=50)
    email=models.EmailField(unique=True)
    subject=models.CharField(max_length=100)
    message=models.CharField(max_length=1000)

    def __str__(self):
        return self.name

class NotesInfo(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,default=1)  
    add_notes=models.TextField(max_length=2000)
    
    def __str__(self):
        return self.add_notes

mysite/templates/all_notes.html
{% extends 'mainpageloggedin.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="container" style="margin:30px auto;">
            <div class="row">
                <div class="container">
                    <div class="mainbuttons">
                        <a href="{% url 'mainpageloggedin' %}" id="addNote" class="btn btn-info btn-lg" > Add Note</a> 
                        <a href="{% url 'display_notes' %}" id="allnotes" class="btn btn-info btn-lg float-right " > All Notes</a>
                    </div>
                    
                </div>
                    
            </div>
<!--#######################################################################################################################-->
        <div class="container" >
            
            <div class="list-group" id="notes_data" style="padding:10px;margin:10px auto">
                                
                {% for value in show_notes %}
                        
                        
                        
                        <div class="container not_empty_data bg-light" style="color:#584153; padding:15px;border-radius:10px;border:1px solid grey; ">
                            <p> {{ value.add_notes|linebreaks }}</p>
                        
                            <a href="{% url 'update_task' value.id %}" class="btn btn-primary" >Update</a>
    <!--------Modal-------------------------------------------------------------------------------------------------->   

                            <a data-toggle="modal" data-target="#fm-modal-grid" class="btn btn-primary float-right temp1" id="{{value.id}}" style="color:white"  >Delete</a>
                                <div class="modal fade" id="fm-modal-grid" tabindex="-1" role="dialog" aria-labelledBy="fm-modal-grid" aria-hidden="true">
                                    <div class="modal-dialog modal-md" id="modal">
                                        <div class="modal-content">
                                            <div class="modal-header bg-light">
                                                <h5 class="modal-title">Delete Confirmation</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body" style="color:black">
                                                <div class="container-fluid">
                                                    <div class="row">
                                                        <div class="col-12 col-sm-12">
                                                            <p>Are you sure you want to delete this Note ?</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="modal-footer">
                                                <form action="{% url 'delete' value.id %}" method="POST">                                
                                                    {% csrf_token %}
                                                    <input type="submit" name="" value="Confirm" class="btn btn-danger float-right">
                                                </form>
                                                <button class="btn btn-primary" data-dismiss="modal">Cancel</button>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </div>
                        <br>
                    

                {% endfor %}
                <div class="container empty_data" >
                                <div class="alert alert-primary" role="alert" >
                                   <i class="fa fa-sticky-note-o" style="color:green;font-size:28px;padding-right:20px"aria-hidden="true"></i> Looks like you don't have any saved notes!{{empty}}
                                </div>
                </div>
                
            </div>
        </div>

        <!-- Modal -->
               
<!--#######################################################################################################################-->
</div>
<script>
    if ($('.not_empty_data').length == 0) {
    $('.empty_data').show()

    }
    else{
        $('.empty_data').hide() 
    }
</script>

{% endblock %}

mysite/templates/base.html
<!doctype html>
{% load static %}
{% load bootstrap4 %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> <link rel="stylesheet" href="{%static 'blog/css/style.css'%}">
    <link rel="stylesheet" href="{%static 'blog/css/style.css'%}">

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>Online Notes</title>
  </head>
  
    <section id="header">
      
            <nav class="navbar navbar-expand-lg navbar-fixed-top navbar-light ">
                 <a class="navbar-brand" style="color:#584153">OnlineNotes</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav " id="navbarContent1">
                        <li class="nav-item active">
                            <a href="{% url 'index'%}" class="nav-link">Home</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'help' %}" class="nav-link" id="help">Help</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'contactus' %}" class="nav-link">Contact us</a>
                        </li>
                        
                    </ul>
                    <ul class="navbar-nav ml-auto" id="navbarContent2" >
                        {% if user.is_authenticated %}
                            <li class="nav-item"> 
                                <a class="nav-link" href="{% url 'logout' %}" class="login_button">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link"  href="{% url 'basic_app:user_login' %}" class="login_button">Login</a>
                            </li>
                        {% endif %}
                        
                    </ul>
                </div>
            </nav>
        
    </section>
    <!--Navigation ends-->

    <div class="container-fluid" id="base_container">
            {% block body_block %}
            
                {% endblock  %}
    </div>
   
    <footer class="footer fixed-bottom ">
        <div class="container footer-copyright text-center py-2">
             <span class="">OnlineNotes.com  Copyright&copy;2019-20</span>
        </div>
    </footer>

</body>
</html>

mysite/templates/contactus.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block body_block %}
<style>
body{
     background: url("{% static 'blog/images/contactsus.jpg' %}") no-repeat center center fixed; 
     background-size: cover;
  
    }

</style>

  <div class="container" style="padding-top:20px" >
        <h3 style="text-align:center;" class="text_clicked">Just fill out the form.</h3>

        <form  method="POST">
          {% csrf_token %}
          {{ contacts|crispy}}
          <div class="text-center">
          <input type="submit" name="" value="Shoot Message" class="btn btn-primary">
          </div>
        </form>

  </div>
  
    <script>
        $('.login_button').hide();
    </script>


{% endblock %}

mysite/templates/delete.html
{% extends 'mainpageloggedin.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
    <form  method="POST">
        {% csrf_token %}
      <input type="submit" name="" value="Confirm" class="btn btn-danger float-right">

            </form>     
  
{% endblock  %}

mysite/templates/help.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
<style>
body{
     background: url("{% static 'blog/images/help.jpg' %}") no-repeat center center fixed; 
     background-size: cover;
    }
</style>
<div class="container" id="help_container" >

 
            <h2>Steps to use this website:</h2>
                <p class="steps">Step1: Signing Up</p>
                <p class="steps_details">Click on the 'SignUp' button. After filling the SignUp form, you'll be redirected to the main page.</p>
                
                <p class="steps">Step2: Loggin In</p>
                <p class="steps_details">Click on the 'Login' link on the navigation bar and enter your email id and password respectively. Click on 'Login' button.</p>
                
                <p class="steps">Step3: My Notes</p>
                <p class="steps_details">I- Click on 'Add Note'.</p>
                <p class="steps_details">II- Click 'Edit' to edit your notes.</p>
                <p class="steps_details">III- Click 'Delete' to delete your notes.</p>
                <p class="steps_details">IV- Click 'All Notes' to see your all saved notes.</p>
                
                
                <p class="steps">User</p>
                <p class="steps_details">Check your username here.</p>
                
                
                <p class="steps">Contact Us</p>
                <p class="steps_details">Click on 'Contact Us' tab to ask any query or to give any complaints/suggestions.</p>
        

            

    </div>
{% endblock %}

mysite/templates/index.html
{% extends 'base.html' %}
{% load static %}
  {% block body_block %}
  <style>
    body{
        background: url("{% static 'blog/images/background.jpg' %}") no-repeat center center fixed; 
        background-size: cover;
  
    }
    </style>
    <section id="main">
        <div class="jumbotron jumbotron-fluid">
                <div class="container">
                    <div class="content">
                        <h1>Online Notes</h1>
                        <p class="lead">
                            Your Notes with you wherever you go <br>Easy to use protects all your notes.
                        </p>
                        <a class="btn btn-primary" href="{% url 'register'%}" class="nav-link">Sign up</a>
                    </div>
                </div>
        </div>
    </section>
    <script>
            $('.first-button').on('click', function () {
                                                            $('.animated-icon1').toggleClass('open');
                                                    });
  </script>
{% endblock %}
    

mysite/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body_block %}
<style>
body{
     background: url("{% static 'blog/images/login.jpg' %}") no-repeat center center fixed; 
     background-size: cover;
    }

</style>


  <div class="container" style="  margin:100px auto;">
      <h1 style="text-align:center;color: #584153;">Login</h1>

        <form method="POST" action="{% url 'user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
            <div class="container" >
                  <div class="form-group">
                      <label for="username"  class="col-sm-2 col-form-label" style="color: #584153;">Username:</label>
                         
                            <input type="text" class="form-control" name="username" placeholder="Username">
                        
                  </div>
                  <div class="form-group">
                      <label for="password" class="col-sm-2 col-form-label" style="color: #584153;">Password:</label>
                          
                            <input type="password" class="form-control" name="password" placeholder="Enter your password">
                         
                  </div>
            </div>
          <div class="text-center">
            <input type="submit" id="login_user" value="Login" class="btn btn-primary">
          </div>
        </form>
        <h5 style="text-align:center;margin-top:20px;color: #584153;" id="text_alert">Forgot your password? <a href="{% url 'reset_password' %}">Click Here</a></h5>

  </div>
  <div class="container" id="saved_messages">
        {% for message in messages %}
            <div class="alert alert-danger" style="font-size:20px;display:inline-block;margin:0px 40% ;">
                {{ message }}
            </div>
        {% endfor %}
  </div>
  <script>
 
    setTimeout(function() {
            $('#saved_messages').fadeOut('slow');
        }, 2000);
  

  
  </script>
  
  
{% endblock %}

mysite/templates/mainpageloggedin.html
<!doctype html>
{% load static %}
{% load crispy_forms_tags %}
<style>
body{
     background: url("{% static 'blog/images/mainpage.jpg' %}") no-repeat center center fixed; 
     background-size: cover;
    }

</style>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> <link rel="stylesheet" href="{%static 'blog/css/style.css'%}">
  <link rel="stylesheet" href="{%static 'blog/css/style.css'%}">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>Online Notes</title>
  </head>
  
    <section id="header">
        
            <nav class="navbar navbar-expand-lg navbar-fixed-top navbar-light bg-light">
                <a class="navbar-brand" >Online Notes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarContent">
                    <ul class="navbar-nav mr-auto ">
                        <li class="nav-item active">
                            <a >Welcome : {{user}}</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                           <li> <a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                        {% else %}
                            <i><a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        
    </section>
    <!--Navigation ends-->
<div class="container">
    
        
    {% block body_block %}
        <div class="container" style="margin:30px auto;">
                <div class="row">
                    <div class="container">
                        <div class="mainbuttons">
                            <a href="{% url 'mainpageloggedin' %}" id="addNote" class="btn btn-info btn-lg" > Add Note</a> 
                            <a href="{% url 'display_notes' %}" id="allnotes" class="btn btn-info btn-lg float-right " > All Notes</a>
                        </div>
                        <div id="notePad" style="margin:10px auto;">
                            <form  method="POST">
                                {% csrf_token %}
                        
                                {{ notes|crispy }}
                    
                                <div class="text-center">
                                    <input  type="submit" value="Save" class="btn btn-primary">
                                </div>
                            </form>     
                        </div>
                    </div>
                </div>
        </div>
        <div id="saved_message">
        {% for message in messages %}
            <div style="text-align:center;font-size:20px">
                </button>
                {{ message }}
            </div>
        {% endfor %}
        </div>
        <!--Main ends-->

    {% endblock %}

</div>
    <footer class="footer fixed-bottom ">
        <div class="container footer-copyright text-center py-2">
             <span class="">OnlineNotes.com  Copyright&copy;2019-20</span>
        </div>
    </footer>
   

    <!-- Optional JavaScript -->

    <script>
         $("#id_user option[value={{user_data}}]").attr('selected', 'selected');
         $("select").hide();
         $('label[for="id_user"]').hide();

        setTimeout(function() {
            $('#saved_message').fadeOut('slow');
        }, 2000);

    </script>


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</body>
</html>

mysite/templates/password_reset.html
{% extends "base.html" %}

{% block body_block %}
{% load crispy_forms_tags %}
{% load static %}
<style>
body{
     background: url("{% static 'blog/images/reset.jpg' %}") no-repeat center center fixed; 
     background-size: cover;
    }
#my_container{
            margin:100px auto;
            color:#584153;
            }
#my_container p{
    color:#0779e4;
}

@media screen and (max-width:900px) {
            #text_click{
                padding-bottom:20px;
                text-align:center;
            }
        }

    
</style>

  <div class="container" id="my_container">
        <h1 style="text-align:center">Password reset</h1>
        <p id="text_click">Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>
        <form method='POST'>
        {{ form|crispy}}
        {% csrf_token %}
        <div class="text-center">
        <input type="submit" value="Change password" class="btn btn-primary">
        </div>
        </form>
    </div>
    <
{% endblock %}

mysite/templates/password_reset_complete.html
{% extends "base.html" %}
{% block body_block %}
{% load crispy_forms_tags %}
{% load static %}

<style>
body{
     background: url("{% static 'blog/images/reset.jpg' %}") no-repeat center center fixed; 
     background-size: cover;
    }
@media screen and (max-width:900px) {
    .container h1{
        font-size:25px;
    }
    .container h5{
        font-size:18px;
    }
}
</style>

<div class="container" style="margin:100px auto;">
<h1 style="color: #584153;text-align:center;padding-bottom:20px">Password reset complete</h1>
<h5 style="color:#0779e4;text-align:center;padding:10px">Your password has been set. You may go ahead and log in now.</h5>
<div class="text-center">
    <a href="{% url 'user_login'%}" class="btn btn-primary btn-lg active">Log In</a>
</div>
    <form method='POST'>
        {% csrf_token %}
        {{ form|crispy }}
    
    </form>
 </div>
{% endblock %}

mysite/templates/password_reset_form.html
{% extends "base.html" %}
{% block body_block %}
{% load crispy_forms_tags %}
{% load static %}

<style>
body{
     background: url("{% static 'blog/images/reset.jpg' %}") no-repeat center center fixed; 
     background-size: cover;
    }
</style>

<div class="container" style="margin:100px auto;">
<h3 style="color: #584153;">Enter new password</h3>


<form method="post">

	{% csrf_token %}
	{{form|crispy}}
    <div class="text-center">
            <input type="Submit"  name="Update Password" value="Update Password" class="btn btn-primary">
    </div>

	
</form>
 </div>
{% endblock %}

mysite/templates/password_reset_sent.html
{% extends "base.html" %}
{% block body_block %}
{% load static %}

<style>
body{
     background: url("{% static 'blog/images/reset.jpg' %}") no-repeat center center fixed; 
     background-size: cover;
    }
#reset_container{
            margin:100px auto;
            color:#0779e4;
            
}

        @media screen and (max-width:900px) {
                #reset_container h5 {
                                    font-size: 15px;
                                    
                                    }
        }

</style>

<div class="container" id="reset_container">
<h5>We’ve emailed you instructions for setting your password, if an account exists with the email you entered.You should receive them shortly.<br><br>
If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
</h5>
 </div>
{% endblock %}

mysite/templates/sign_up.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block body_block %}
<style>
body{
     background: url("{% static 'blog/images/login.jpg' %}") no-repeat center center fixed; 
     background-size: cover;
    }
</style>

<section >
  <div class="container" style="padding:0px 200px;margin-bottom:60px">
      {% if registered %}
        <h5 style="text-align:center;">Thank you for registering!</h5>
                
        <script>
        setTimeout(function() {
                $.get("{% url 'mainpageloggedin' %}") // Do something after 5 seconds
            }, 5000);


        </script>
      {% else %}
        <h3 style="text-align:center;padding:10px;">Register Here</h3>
        <form  method="POST" >
        {% csrf_token %}
              {{ user_form|crispy }}
          <div class="text-center">
          <input type="submit" name="" value="Register" class="btn btn-primary">
          </div>
          </div>
        </form>

      {% endif %}

  </div>
</section>
{% endblock %}

mysite/templates/update_task.html
{% extends 'mainpageloggedin.html' %}
{% block body_block %}
{% load crispy_forms_tags %}

    <div class="container" style="margin:50px auto;position:absolute;padding:20px"> 
            <h3 style="margin-bottom:20px;">Update Notes</h3>
            <div class="container">
                <form  method="POST">
        
                                {% csrf_token %}
                                {{ form|crispy }}
                            
                                <div class="text-center">
                                    <input type="submit" name="" value="Update" class="btn btn-primary">
                                </div>
                                
                </form> 
            </div>        
    </div>
    <script>
     $('#div_id_user').hide();
    </script>
{% endblock  %}